### ISSUE TITLE
Is it possible to limit the color range?

### ISSUE THREAD

**Issue by erichaus** [IonicaBizau/flat-colors.js#16]
Hello, is it possible to limit the color range to e.g. blues/teals/greens/light red? and exclude anything that is gray/black/white/etc?

**Comment by erichaus** [comment]
for random flat color

**Comment by IonicaBizau** [comment]
It was not possible yesterday, but it's possible today:
—https://github.com/IonicaBizau/random-flat-colors 🎉

**Comment by erichaus** [comment]
haha good job @IonicaBizau way to go 👍

**Comment by IonicaBizau** [comment]
😁

**Comment by IonicaBizau** [comment]
You're welcome! 👍
